name: Update Changelog

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build the Docker container
      run: docker build -t auto-changelog -f Dockerfile.auto-changelog .

    - name: Run the container
      run: docker run --rm -v "${{ github.workspace }}:/app" auto-changelog

    - name: Commit and push changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add CHANGELOG.md
        git commit -m "Update changelog"
        git push origin HEAD:main